language: scala
scala:
  - 2.11.8

jdk:
  - oraclejdk8

script:
  - sbt clean coverage test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash) -t "08f82a2a-493d-4766-b866-3fe5479cac82"
